config/routes.rb
Meudinheiro::Application.routes.draw do
  resources :transactions
  

end

app/models/transaction.rb
# encoding: UTF-8
class Transaction < ActiveRecord::Base
  attr_accessible :category_id, :description, :transaction_date, :user_id, :value

  validate :transaction_date_is_a_time_object

  def initialize(attributes = {})
    super
    @category_id = attributes[:category_id]
    @description = attributes[:description]
    unless attributes[:transaction_date].nil? || attributes[:transaction_date].empty?
      begin
        @transaction_date = Date.parse(attributes[:transaction_date]) 
      rescue
        @transaction_date = nil
      end
    end
    @user_id = attributes[:user_id]
    @value = attributes[:value]
  end

  def transaction_date_is_a_time_object
    if @transaction_date.nil? || @transaction_date.class != Date then
      errors.add(:transaction_date, "A data está vazia ou inválida")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def new
    @transaction = Transaction.new
  end

  def create
    @transaction = Transaction.new(params[:transaction])
    if @transaction.save
      redirect_to transactions_path
    else
      flash.now[:error] = @transaction.errors.messages
      render 'new'
    end
  end

  def update
  end

  def edit
  end

  def destroy
  end

  def index
    per_page = 3
    @pg = params[:pg].to_i || 1
    @total_pages = Transaction.count/per_page
    @transactions = Transaction.order("transaction_date DESC").limit(per_page).offset(@pg * per_page - per_page)
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_message
    if flash.count > 0 then
      messages_list = []
      [:notice, :info, :warning, :error].each do |type|
        if flash[type] then
          flash[type].each do |field, messages| 
            messages.each { |message| messages_list << message }
          end
        end
      end

      messages_list
    end
  end

  def show_errors(messages)
    errors_html = '<ul>'
    messages.each { |msg| errors_html << "<li>#{msg}</li>" }
    errors_html << '</ul>'
    raw errors_html
  end

  def get_last_transactions
    transactions = Transaction.order("transaction_date DESC").limit(10)
    transactions.each { |transaction| yield transaction }
  end

  def final_balance
    Transaction.sum('value')
  end
end

app/helpers/bootstrap_helper.rb
module BootstrapHelper
  def print_field(form, element, label, field, size = 'medium')
    label = form.label field, label, :class => "control-label"
    form_field = form.send(element, field, { :class=> "input-#{size}" })
    div_control = content_tag(:div, form_field, :class => "controls")
    content = label+div_control
    print_element(content)
  end

  def print_submit(form, text)
    submit_button = form.send(:submit, text, {:class => "btn btn-success"})
    content = content_tag(:div, submit_button, :class => "controls")
    print_element(content)
  end

  def print_element(content)
    content_tag(:div, content, :class => "control-group")
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Meu Dinheiro</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
 <div class="navbar navbar-fixed-top">
   <div class="navbar-inner">
     <div class="container">
       <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
       </a>
       <a class="brand" href="../">Meu Dinheiro</a>
       <div class="nav-collapse" id="main-menu">
        <ul class="nav" id="main-menu-left">
          <li><a href="<%= transactions_path %>"><i class="icon-white icon-retweet"></i> Movimentações</a></li>
          <li><a href="<%= transactions_path %>"><i class="icon-white icon-calendar"></i> Calendário</a></li>
        </ul>
        <ul class="nav pull-right" id="main-menu-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" title="Minha conta"><i class="icon-white icon-home"></i> Diogo Benicá <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><a href="#">Minha conta</a></li>
              <li class="divider"></li>
              <li><a href="#">Sair</a></li>
            </ul>
          </li>
          <li></li>
        </ul>
       </div>
     </div>
   </div>
 </div>

 <div class="container" id="master-container">
   <% if errors = flash_message %>
   <div class="row">
     <div class="span12">
       <div class="alert alert-error">
         <%= show_errors errors %>
       </div>
     </div>
   </div>
   <% end %>
   <div class="row">
     <div class="span3">
      <h4>Últimas movimentações</h4>
     	<table class="table last-transactions table-bordered">
     	  <tr>
          <th class="last-transactions-subheader">Descrição</th>
          <th class="last-transactions-subheader"><span class="label label-warning">Saídas</span></th>
     	  	<th class="last-transactions-subheader"><span class="label label-success">Entradas</span></th>
     	  </tr>
   	  	<% get_last_transactions do |transaction| %>
          <tr>
            <td>
              <%= 
              if transaction.description.length > 20 then
                "#{transaction.description[0,19]}..."
              else
                transaction.description
              end
              %>
            </td>
            <td class="last-transaction-negative"><%= transaction.value if transaction.value < 0 %></td>
            <td class="last-transaction-positive"><%= transaction.value if transaction.value > 0 %></td>
          </tr>
        <% end %>
        <tr>
          <td class="final_balance">Saldo</td>
          <td colspan="2" class="final_balance"><%= final_balance %></td>
        </tr>
     	</table>
     </div>
     <div class="span9">
     	<%= yield %>
     </div>
   </div>
</body>
</html>

app/views/transactions/create.html.erb
<h1>Transactions#create</h1>
<p>Find me in app/views/transactions/create.html.erb</p>

app/views/transactions/destroy.html.erb
<h1>Transactions#destroy</h1>
<p>Find me in app/views/transactions/destroy.html.erb</p>

app/views/transactions/edit.html.erb
<h1>Transactions#edit</h1>
<p>Find me in app/views/transactions/edit.html.erb</p>

app/views/transactions/index.html.erb
<div>
	<h1 class="pull-left">Movimentações</h1>
	<div class="pull-right">
		<ul class="pager">
			<li><a class="action" href="<%= new_transaction_path %>"><i class="icon-plus"></i> Nova</a></li>
		</ul>
	</div>
</div>
<table class="table table-bordered table-striped">
	<thead>
		<tr>
	    	<th>Data</th>
	    	<th>Descrição</th>
	    	<th>Valor</th>
	  	</tr>
	</thead>
	<tbody>
		<% @transactions.each do |transaction| %>
		<tr>
	    	<td><%= transaction.transaction_date %></td>
	    	<td><%= transaction.description %></td>
	    	<td><%= transaction.value %></td>
	    </tr>
	    <% end %>
	</tbody>
</table>
<div class="pagination pagination-centered">
	<ul>
	<% @total_pages.times do |page| %>
		<li <%= raw 'class="active"' if @pg == page+1 %>>
			<a href="<%= transactions_path %>?pg=<%= page+1 %>"><%= page+1 %></a>
		</li>	
	<% end %>
	</ul>
</div>

app/views/transactions/new.html.erb
<%= form_for @transaction, :html => { :class => "form-horizontal well" } do |f| %>
  <fieldset>
	<legend>Nova movimentação</legend>
	  <%= print_field f, :text_field, "Valor", :value, 'small' %>
	  <%= print_field f, :text_field, "Descrição", :description %>
	  <%= print_field f, :text_field, "Data", :transaction_date, 'small date' %>
	<%= print_submit f, "Salvar" %>
  </fieldset>
<% end %>

app/views/transactions/show.html.erb
<h1>Transactions#show</h1>
<p>Find me in app/views/transactions/show.html.erb</p>

app/views/transactions/update.html.erb
<h1>Transactions#update</h1>
<p>Find me in app/views/transactions/update.html.erb</p>